### ISSUE TITLE
Search bar is positioned off screen on right side allignment

### ISSUE THREAD

**Issue by smeijer** [smeijer/leaflet-geosearch#93]
![image](https://cloud.githubusercontent.com/assets/1196524/22426607/33839a7a-e700-11e6-813a-46036f39dab4.png)

As discovered while solving #92

**Comment by smeijer** [comment]
Fix:

```css
.leaflet-right .leaflet-control-geosearch form {
  right: 28px;
  left: initial;
  border-radius: 4px 0 0 4px;
  border-left: inherit;
  border-right: none;
}
```
